base:
   system: jamip
   lreal: Auto
   ismear: 0
   npar: 4
   sigma: 0.05
   algo: normal
relax:
   nsw: 60
   addgrid: true
scf:
   lcharg: true
soc:
   isym: 0
   lmaxmix: 6
   ispin: 2
   gga_compat: true
   lorbmom: true
   lsorbit: true
   saxis: 0 0 1
hse:
   aexx: 0.25
   hfscreen: 0.2
   icharg: 0
   algo: Damped
   lhfcalc: true
   lwave: true
   lmaxfock: 4
   time: 0.4
band:
   icharg: 11
   lorbit: 11
emass:
   icharg: 11
   lorbit: 11
dos:
   ismear: -5
   nedos: 3001
   lwave: false
   lorbit: 11
optics:
   istart: 0
   icharg: 11
   lwave: true
   lcharg: false
   loptics: true
   algo: normal
   cshift: 0.02
   nedos: 3001
   npar: 1
gw:
   lspectral: true
   nelm: 3
   algo: scGW
   ismear: 0
   sigma: 0.05
   loptics: true
   cshift: 0.05
   lcharg: false
   nedos: 3001
stm:
   lpard: true
   lsepk: false
   lsepb: false
   nbmod: -3
   eint: -0.1
   lorbit: 11
   lwave: false
   lcharg: false
Raman:
   isym: 0
   nwrite: 3
   ibrion: 7
   lreal: false
   lepsilon: true
   nsw: 1
nve:
   nsw: 100
   nelmin: 3
   potim: 1
   smass: -3
   tebeg: 300
   teend: 300
nvt:
   nsw: 100
   nelmin: 3
   iwavpr: 11
   potim: 1
   smass: 0
   tebeg: 300
   teend: 300
npt:
   nsw: 100
   nelmin: 3
   mdalgo: 3
   langevin_gamma: 10 10
   langevin_gamma_l: 1
   potim: 1
   pmass: 5
   pstress: 1
   tebeg: 300
   teend: 300
force:
   dim: 1 1 1
   symprec: 0.001
   parallel: 1
softmode:
   dimension: 1 1 1
   q: 0 0 0
   band_index: 0
   amplitude: 0.0 10.0 0.5
   argument: 0
   parallel: 1
gruneisen:
   nsw: 50
   isif: 4
   ibrion: 2
   scale: 0.05
   parallel: 1
partchg:
   lwave: false
   lcharg: false
   lpard: true
   lsepb: true
   lorbit: 11
   nsw: 0
dielectric:
   ibrion: 8
   lcharg: false
   lwave: false
   istart: 0
   icharg: 2
   nsw: 2
   lepsilon: true
   lpead: true
elastic:
   lcharg: false
   lwave: false
   ibrion: 6
   isif: 3
   nfree: 4
